"""Public package surface for the standalone Advisor product."""

from .api import create_gateway, create_http_app, create_orchestrator, get_version, run_task
from .benchmark import (
    BenchmarkCase,
    BenchmarkRunManifest,
    BenchmarkSuite,
    build_benchmark_run_manifest,
    compare_benchmark_arms,
    freeze_benchmark_suite,
)
from .gateway import AdvisorGateway
from .hardening import (
    BenchmarkReleasePolicy,
    DeploymentHardeningProfile,
    build_alert_summary,
    build_deployment_hardening_profile,
    evaluate_release_gate,
    export_product_bundle,
    import_product_bundle,
    lock_truth_surface_contract,
)
from .integrations import (
    BuildTestCommandVerifier,
    CodingAgentSubprocessExecutor,
    DomainWorkerSubprocessExecutor,
    FrontierHTTPExecutor,
    HumanReviewFileVerifier,
    IntegrationRegistry,
    RubricTextVerifier,
    ScreenshotHashVerifier,
)
from .observability import (
    LiveMetricsSnapshot,
    RunEventLogger,
    build_audit_report,
    export_live_metrics,
    redact_packet,
)
from .operator_runtime import (
    DeploymentProfile,
    OperatorJobQueue,
    OperatorJobRecord,
    OperatorJobRequest,
    RetentionEnforcer,
    build_deployment_profile,
    build_operator_snapshot,
)
from .orchestration import (
    AdvisorOrchestrator,
    BuildTestVerifier,
    CodingAgentExecutor,
    DeterministicABRouter,
    DomainWorkerExecutor,
    FrontierChatExecutor,
    HumanReviewVerifier,
    RubricVerifier,
    ScreenshotComparisonVerifier,
)
from .profiles import AdvisorProfile, AdvisorProfileRegistry, AdvisorTrainingConfig
from .results_pass import (
    build_failure_taxonomy,
    build_phase16_results_report,
    default_paper_divergences,
    summarize_ablation_results,
    summarize_canonical_study,
    summarize_provenance_coverage,
    summarize_transfer_results,
    write_phase16_results_report,
)
from .reward_registry import RewardRegistry
from .reward_specs import RewardSpec
from .schemas import (
    AdviceBlock,
    AdvisorInputPacket,
    AdvisorOutcome,
    AdvisorTaskRequest,
    AdvisorTaskRunResult,
)
from .settings import AdvisorSettings
from .training_backends import GRPOTrainingBackend, TrainingBackendRunRequest, TrainingBackendRunResult
from .training_rollouts import (
    RolloutTurnRecord,
    TrainingRolloutGroupRequest,
    TrainingRolloutGroupResult,
    TrainingRolloutRequest,
    TrainingRolloutResult,
    execute_training_rollout,
    execute_training_rollout_group,
)
from .training_runtime import (
    CheckpointLifecycleManager,
    ProfileCheckpointEvaluation,
    TrainingCheckpointRecord,
    TrainingJobConfig,
    TrainingJobResult,
    evaluate_profile_checkpoint_for_promotion,
    evaluate_trained_checkpoint,
    run_profile_training_job,
)
from .version import __version__

# Keep __all__ narrow so external callers depend on stable entrypoints only.
__all__ = [
    "__version__",
    "AdviceBlock",
    "AdvisorGateway",
    "AdvisorProfile",
    "AdvisorProfileRegistry",
    "AdvisorTrainingConfig",
    "AdvisorInputPacket",
    "AdvisorOrchestrator",
    "AdvisorOutcome",
    "AdvisorSettings",
    "AdvisorTaskRequest",
    "AdvisorTaskRunResult",
    "RewardRegistry",
    "RewardSpec",
    "BenchmarkCase",
    "BenchmarkReleasePolicy",
    "BenchmarkRunManifest",
    "BenchmarkSuite",
    "BuildTestCommandVerifier",
    "BuildTestVerifier",
    "CheckpointLifecycleManager",
    "CodingAgentExecutor",
    "CodingAgentSubprocessExecutor",
    "DeploymentHardeningProfile",
    "DeploymentProfile",
    "DeterministicABRouter",
    "DomainWorkerExecutor",
    "DomainWorkerSubprocessExecutor",
    "FrontierChatExecutor",
    "FrontierHTTPExecutor",
    "GRPOTrainingBackend",
    "HumanReviewFileVerifier",
    "HumanReviewVerifier",
    "IntegrationRegistry",
    "LiveMetricsSnapshot",
    "OperatorJobQueue",
    "OperatorJobRecord",
    "OperatorJobRequest",
    "ProfileCheckpointEvaluation",
    "RetentionEnforcer",
    "RubricVerifier",
    "RubricTextVerifier",
    "RunEventLogger",
    "ScreenshotComparisonVerifier",
    "ScreenshotHashVerifier",
    "TrainingCheckpointRecord",
    "TrainingBackendRunRequest",
    "TrainingBackendRunResult",
    "TrainingJobConfig",
    "TrainingJobResult",
    "TrainingRolloutGroupRequest",
    "TrainingRolloutGroupResult",
    "TrainingRolloutRequest",
    "TrainingRolloutResult",
    "build_alert_summary",
    "build_audit_report",
    "build_benchmark_run_manifest",
    "build_deployment_hardening_profile",
    "build_deployment_profile",
    "build_failure_taxonomy",
    "build_operator_snapshot",
    "build_phase16_results_report",
    "compare_benchmark_arms",
    "create_gateway",
    "create_http_app",
    "create_orchestrator",
    "default_paper_divergences",
    "evaluate_profile_checkpoint_for_promotion",
    "evaluate_release_gate",
    "evaluate_trained_checkpoint",
    "export_live_metrics",
    "export_product_bundle",
    "freeze_benchmark_suite",
    "get_version",
    "import_product_bundle",
    "lock_truth_surface_contract",
    "redact_packet",
    "run_profile_training_job",
    "run_task",
    "summarize_ablation_results",
    "summarize_canonical_study",
    "summarize_provenance_coverage",
    "summarize_transfer_results",
    "write_phase16_results_report",
    "RolloutTurnRecord",
    "execute_training_rollout",
    "execute_training_rollout_group",
]
