"""Public package surface for the standalone Advisor product."""

from .core.schemas import (
    AdviceBlock,
    AdvisorInputPacket,
    AdvisorOutcome,
    AdvisorTaskRequest,
    AdvisorTaskRunResult,
)
from .core.settings import AdvisorSettings
from .core.version import __version__
from .evaluation.benchmark import (
    BenchmarkCase,
    BenchmarkRunManifest,
    BenchmarkSuite,
    build_benchmark_run_manifest,
    compare_benchmark_arms,
    freeze_benchmark_suite,
)
from .evaluation.results_pass import (
    build_failure_taxonomy,
    build_phase16_results_report,
    default_paper_divergences,
    summarize_ablation_results,
    summarize_canonical_study,
    summarize_provenance_coverage,
    summarize_transfer_results,
    write_phase16_results_report,
)
from .execution.integrations import (
    BuildTestCommandVerifier,
    CodingAgentSubprocessExecutor,
    DomainWorkerSubprocessExecutor,
    FrontierHTTPExecutor,
    HumanReviewFileVerifier,
    IntegrationRegistry,
    RubricTextVerifier,
    ScreenshotHashVerifier,
)
from .execution.orchestration import (
    AdvisorOrchestrator,
    BuildTestVerifier,
    CodingAgentExecutor,
    DeterministicABRouter,
    DomainWorkerExecutor,
    FrontierChatExecutor,
    HumanReviewVerifier,
    RubricVerifier,
    ScreenshotComparisonVerifier,
)
from .operators.operator_runtime import (
    ContinuousTrainingCycleResult,
    DeploymentProfile,
    EvalProfileJobPayload,
    OperatorJobQueue,
    OperatorJobRecord,
    OperatorJobRequest,
    PromoteCheckpointJobPayload,
    RetentionEnforcer,
    TrainProfileJobPayload,
    build_deployment_profile,
    build_operator_snapshot,
    run_continuous_training_cycle,
    run_operator_job,
)
from .product.api import create_gateway, create_http_app, create_orchestrator, get_version, run_task
from .product.gateway import AdvisorGateway
from .product.hardening import (
    BenchmarkReleasePolicy,
    DeploymentHardeningProfile,
    build_alert_summary,
    build_deployment_hardening_profile,
    evaluate_release_gate,
    export_product_bundle,
    import_product_bundle,
    lock_truth_surface_contract,
)
from .profiles.profiles import AdvisorProfile, AdvisorProfileRegistry, AdvisorTrainingConfig
from .rewards.reward_registry import RewardRegistry
from .rewards.reward_specs import RewardSpec
from .storage.observability import (
    LiveMetricsSnapshot,
    RunEventLogger,
    build_audit_report,
    export_live_metrics,
    redact_packet,
)
from .training.training_backends import (
    GRPOTrainingBackend,
    MLXLoRATrainer,
    TrainerRunArtifact,
    TrainingBackendRunRequest,
    TrainingBackendRunResult,
)
from .training.training_rollouts import (
    RolloutTurnRecord,
    TrainingRolloutGroupRequest,
    TrainingRolloutGroupResult,
    TrainingRolloutRequest,
    TrainingRolloutResult,
    execute_training_rollout,
    execute_training_rollout_group,
)
from .training.training_runtime import (
    CheckpointLifecycleManager,
    ProfileCheckpointEvaluation,
    TrainingCheckpointRecord,
    TrainingJobConfig,
    TrainingJobResult,
    evaluate_profile_checkpoint_for_promotion,
    evaluate_trained_checkpoint,
    resolve_active_profile_checkpoint_metadata,
    run_profile_training_job,
)

# Keep __all__ narrow so external callers depend on stable entrypoints only.
__all__ = [
    "__version__",
    "AdviceBlock",
    "AdvisorGateway",
    "AdvisorProfile",
    "AdvisorProfileRegistry",
    "AdvisorTrainingConfig",
    "AdvisorInputPacket",
    "AdvisorOrchestrator",
    "AdvisorOutcome",
    "AdvisorSettings",
    "AdvisorTaskRequest",
    "AdvisorTaskRunResult",
    "RewardRegistry",
    "RewardSpec",
    "BenchmarkCase",
    "BenchmarkReleasePolicy",
    "BenchmarkRunManifest",
    "BenchmarkSuite",
    "BuildTestCommandVerifier",
    "BuildTestVerifier",
    "CheckpointLifecycleManager",
    "CodingAgentExecutor",
    "CodingAgentSubprocessExecutor",
    "ContinuousTrainingCycleResult",
    "DeploymentHardeningProfile",
    "DeploymentProfile",
    "DeterministicABRouter",
    "DomainWorkerExecutor",
    "DomainWorkerSubprocessExecutor",
    "FrontierChatExecutor",
    "FrontierHTTPExecutor",
    "GRPOTrainingBackend",
    "HumanReviewFileVerifier",
    "HumanReviewVerifier",
    "IntegrationRegistry",
    "LiveMetricsSnapshot",
    "MLXLoRATrainer",
    "EvalProfileJobPayload",
    "OperatorJobQueue",
    "OperatorJobRecord",
    "OperatorJobRequest",
    "PromoteCheckpointJobPayload",
    "ProfileCheckpointEvaluation",
    "RetentionEnforcer",
    "TrainProfileJobPayload",
    "TrainerRunArtifact",
    "RubricVerifier",
    "RubricTextVerifier",
    "RunEventLogger",
    "ScreenshotComparisonVerifier",
    "ScreenshotHashVerifier",
    "TrainingCheckpointRecord",
    "TrainingBackendRunRequest",
    "TrainingBackendRunResult",
    "TrainingJobConfig",
    "TrainingJobResult",
    "TrainingRolloutGroupRequest",
    "TrainingRolloutGroupResult",
    "TrainingRolloutRequest",
    "TrainingRolloutResult",
    "build_alert_summary",
    "build_audit_report",
    "build_benchmark_run_manifest",
    "build_deployment_hardening_profile",
    "build_deployment_profile",
    "build_failure_taxonomy",
    "build_operator_snapshot",
    "build_phase16_results_report",
    "compare_benchmark_arms",
    "create_gateway",
    "create_http_app",
    "create_orchestrator",
    "default_paper_divergences",
    "evaluate_profile_checkpoint_for_promotion",
    "evaluate_release_gate",
    "evaluate_trained_checkpoint",
    "export_live_metrics",
    "export_product_bundle",
    "freeze_benchmark_suite",
    "get_version",
    "import_product_bundle",
    "lock_truth_surface_contract",
    "redact_packet",
    "resolve_active_profile_checkpoint_metadata",
    "run_continuous_training_cycle",
    "run_operator_job",
    "run_profile_training_job",
    "run_task",
    "summarize_ablation_results",
    "summarize_canonical_study",
    "summarize_provenance_coverage",
    "summarize_transfer_results",
    "write_phase16_results_report",
    "RolloutTurnRecord",
    "execute_training_rollout",
    "execute_training_rollout_group",
]
