"""Public package surface for the standalone Advisor product."""

from .api import create_gateway, create_http_app, create_orchestrator, get_version, run_task
from .benchmark import (
    BenchmarkCase,
    BenchmarkRunManifest,
    BenchmarkSuite,
    build_benchmark_run_manifest,
    compare_benchmark_arms,
    freeze_benchmark_suite,
)
from .gateway import AdvisorGateway
from .integrations import (
    BuildTestCommandVerifier,
    CodingAgentSubprocessExecutor,
    DomainWorkerSubprocessExecutor,
    FrontierHTTPExecutor,
    HumanReviewFileVerifier,
    IntegrationRegistry,
    RubricTextVerifier,
    ScreenshotHashVerifier,
)
from .observability import (
    LiveMetricsSnapshot,
    RunEventLogger,
    build_audit_report,
    export_live_metrics,
    redact_packet,
)
from .operator_runtime import (
    DeploymentProfile,
    OperatorJobQueue,
    OperatorJobRecord,
    OperatorJobRequest,
    RetentionEnforcer,
    build_deployment_profile,
    build_operator_snapshot,
)
from .orchestration import (
    AdvisorOrchestrator,
    BuildTestVerifier,
    CodingAgentExecutor,
    DeterministicABRouter,
    DomainWorkerExecutor,
    FrontierChatExecutor,
    HumanReviewVerifier,
    RubricVerifier,
    ScreenshotComparisonVerifier,
)
from .results_pass import (
    build_failure_taxonomy,
    build_phase16_results_report,
    default_paper_divergences,
    summarize_ablation_results,
    summarize_canonical_study,
    summarize_provenance_coverage,
    summarize_transfer_results,
    write_phase16_results_report,
)
from .schemas import (
    AdviceBlock,
    AdvisorInputPacket,
    AdvisorOutcome,
    AdvisorTaskRequest,
    AdvisorTaskRunResult,
)
from .settings import AdvisorSettings
from .training_runtime import (
    CheckpointLifecycleManager,
    TrainingCheckpointRecord,
    TrainingJobConfig,
    TrainingJobResult,
    evaluate_trained_checkpoint,
)
from .version import __version__

# Keep __all__ narrow so external callers depend on stable entrypoints only.
__all__ = [
    "__version__",
    "AdviceBlock",
    "AdvisorGateway",
    "AdvisorInputPacket",
    "AdvisorOrchestrator",
    "AdvisorOutcome",
    "AdvisorSettings",
    "AdvisorTaskRequest",
    "AdvisorTaskRunResult",
    "BenchmarkCase",
    "BenchmarkRunManifest",
    "BenchmarkSuite",
    "BuildTestCommandVerifier",
    "BuildTestVerifier",
    "CheckpointLifecycleManager",
    "CodingAgentExecutor",
    "CodingAgentSubprocessExecutor",
    "DeterministicABRouter",
    "DomainWorkerExecutor",
    "DomainWorkerSubprocessExecutor",
    "DeploymentProfile",
    "FrontierChatExecutor",
    "FrontierHTTPExecutor",
    "HumanReviewFileVerifier",
    "HumanReviewVerifier",
    "IntegrationRegistry",
    "LiveMetricsSnapshot",
    "OperatorJobQueue",
    "OperatorJobRecord",
    "OperatorJobRequest",
    "RetentionEnforcer",
    "RubricVerifier",
    "RubricTextVerifier",
    "RunEventLogger",
    "ScreenshotComparisonVerifier",
    "ScreenshotHashVerifier",
    "TrainingCheckpointRecord",
    "build_failure_taxonomy",
    "build_phase16_results_report",
    "default_paper_divergences",
    "summarize_ablation_results",
    "summarize_canonical_study",
    "summarize_provenance_coverage",
    "summarize_transfer_results",
    "TrainingJobConfig",
    "TrainingJobResult",
    "build_audit_report",
    "build_benchmark_run_manifest",
    "build_deployment_profile",
    "build_operator_snapshot",
    "compare_benchmark_arms",
    "create_gateway",
    "create_http_app",
    "create_orchestrator",
    "evaluate_trained_checkpoint",
    "export_live_metrics",
    "freeze_benchmark_suite",
    "get_version",
    "redact_packet",
    "run_task",
    "write_phase16_results_report",
]
